/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { AddCommentRequestDto } from '../model/addCommentRequestDto';
// @ts-ignore
import { ApiResponseCommentDto } from '../model/apiResponseCommentDto';
// @ts-ignore
import { ApiResponseListCommentDto } from '../model/apiResponseListCommentDto';
// @ts-ignore
import { ApiResponseListTaskDto } from '../model/apiResponseListTaskDto';
// @ts-ignore
import { ApiResponsePagedResultTaskDto } from '../model/apiResponsePagedResultTaskDto';
// @ts-ignore
import { ApiResponseString } from '../model/apiResponseString';
// @ts-ignore
import { ApiResponseTaskDto } from '../model/apiResponseTaskDto';
// @ts-ignore
import { AssignTaskRequestDto } from '../model/assignTaskRequestDto';
// @ts-ignore
import { ClaimTaskRequestDto } from '../model/claimTaskRequestDto';
// @ts-ignore
import { CompleteTaskRequestDto } from '../model/completeTaskRequestDto';
// @ts-ignore
import { PagedRequestTaskFilterDto } from '../model/pagedRequestTaskFilterDto';
// @ts-ignore
import { UnassignTaskRequestDto } from '../model/unassignTaskRequestDto';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class TaskBpmApiService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @param xApiRequestId 
     * @param xApiCanal 
     * @param taskId 
     * @param addCommentRequestDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addComment(xApiRequestId: string, xApiCanal: string, taskId: string, addCommentRequestDto: AddCommentRequestDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseCommentDto>;
    public addComment(xApiRequestId: string, xApiCanal: string, taskId: string, addCommentRequestDto: AddCommentRequestDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseCommentDto>>;
    public addComment(xApiRequestId: string, xApiCanal: string, taskId: string, addCommentRequestDto: AddCommentRequestDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseCommentDto>>;
    public addComment(xApiRequestId: string, xApiCanal: string, taskId: string, addCommentRequestDto: AddCommentRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (xApiRequestId === null || xApiRequestId === undefined) {
            throw new Error('Required parameter xApiRequestId was null or undefined when calling addComment.');
        }
        if (xApiCanal === null || xApiCanal === undefined) {
            throw new Error('Required parameter xApiCanal was null or undefined when calling addComment.');
        }
        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling addComment.');
        }
        if (addCommentRequestDto === null || addCommentRequestDto === undefined) {
            throw new Error('Required parameter addCommentRequestDto was null or undefined when calling addComment.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xApiRequestId !== undefined && xApiRequestId !== null) {
            localVarHeaders = localVarHeaders.set('x-api-requestId', String(xApiRequestId));
        }
        if (xApiCanal !== undefined && xApiCanal !== null) {
            localVarHeaders = localVarHeaders.set('x-api-canal', String(xApiCanal));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/api/ui/task/${this.configuration.encodeParam({name: "taskId", value: taskId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/comment`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseCommentDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: addCommentRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param xApiRequestId 
     * @param xApiCanal 
     * @param assignTaskRequestDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public assignTasks(xApiRequestId: string, xApiCanal: string, assignTaskRequestDto: AssignTaskRequestDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseListTaskDto>;
    public assignTasks(xApiRequestId: string, xApiCanal: string, assignTaskRequestDto: AssignTaskRequestDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseListTaskDto>>;
    public assignTasks(xApiRequestId: string, xApiCanal: string, assignTaskRequestDto: AssignTaskRequestDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseListTaskDto>>;
    public assignTasks(xApiRequestId: string, xApiCanal: string, assignTaskRequestDto: AssignTaskRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (xApiRequestId === null || xApiRequestId === undefined) {
            throw new Error('Required parameter xApiRequestId was null or undefined when calling assignTasks.');
        }
        if (xApiCanal === null || xApiCanal === undefined) {
            throw new Error('Required parameter xApiCanal was null or undefined when calling assignTasks.');
        }
        if (assignTaskRequestDto === null || assignTaskRequestDto === undefined) {
            throw new Error('Required parameter assignTaskRequestDto was null or undefined when calling assignTasks.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xApiRequestId !== undefined && xApiRequestId !== null) {
            localVarHeaders = localVarHeaders.set('x-api-request-id', String(xApiRequestId));
        }
        if (xApiCanal !== undefined && xApiCanal !== null) {
            localVarHeaders = localVarHeaders.set('x-api-canal', String(xApiCanal));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/api/ui/task/assign`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseListTaskDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: assignTaskRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param xApiRequestId 
     * @param xApiCanal 
     * @param taskId 
     * @param claimTaskRequestDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public claimTask(xApiRequestId: string, xApiCanal: string, taskId: string, claimTaskRequestDto: ClaimTaskRequestDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseString>;
    public claimTask(xApiRequestId: string, xApiCanal: string, taskId: string, claimTaskRequestDto: ClaimTaskRequestDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseString>>;
    public claimTask(xApiRequestId: string, xApiCanal: string, taskId: string, claimTaskRequestDto: ClaimTaskRequestDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseString>>;
    public claimTask(xApiRequestId: string, xApiCanal: string, taskId: string, claimTaskRequestDto: ClaimTaskRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (xApiRequestId === null || xApiRequestId === undefined) {
            throw new Error('Required parameter xApiRequestId was null or undefined when calling claimTask.');
        }
        if (xApiCanal === null || xApiCanal === undefined) {
            throw new Error('Required parameter xApiCanal was null or undefined when calling claimTask.');
        }
        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling claimTask.');
        }
        if (claimTaskRequestDto === null || claimTaskRequestDto === undefined) {
            throw new Error('Required parameter claimTaskRequestDto was null or undefined when calling claimTask.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xApiRequestId !== undefined && xApiRequestId !== null) {
            localVarHeaders = localVarHeaders.set('x-api-requestId', String(xApiRequestId));
        }
        if (xApiCanal !== undefined && xApiCanal !== null) {
            localVarHeaders = localVarHeaders.set('x-api-canal', String(xApiCanal));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/api/ui/task/${this.configuration.encodeParam({name: "taskId", value: taskId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/claim`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseString>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: claimTaskRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param xApiRequestId 
     * @param xApiCanal 
     * @param taskId 
     * @param completeTaskRequestDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public completeTask(xApiRequestId: string, xApiCanal: string, taskId: string, completeTaskRequestDto?: CompleteTaskRequestDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseTaskDto>;
    public completeTask(xApiRequestId: string, xApiCanal: string, taskId: string, completeTaskRequestDto?: CompleteTaskRequestDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseTaskDto>>;
    public completeTask(xApiRequestId: string, xApiCanal: string, taskId: string, completeTaskRequestDto?: CompleteTaskRequestDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseTaskDto>>;
    public completeTask(xApiRequestId: string, xApiCanal: string, taskId: string, completeTaskRequestDto?: CompleteTaskRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (xApiRequestId === null || xApiRequestId === undefined) {
            throw new Error('Required parameter xApiRequestId was null or undefined when calling completeTask.');
        }
        if (xApiCanal === null || xApiCanal === undefined) {
            throw new Error('Required parameter xApiCanal was null or undefined when calling completeTask.');
        }
        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling completeTask.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xApiRequestId !== undefined && xApiRequestId !== null) {
            localVarHeaders = localVarHeaders.set('x-api-requestId', String(xApiRequestId));
        }
        if (xApiCanal !== undefined && xApiCanal !== null) {
            localVarHeaders = localVarHeaders.set('x-api-canal', String(xApiCanal));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/api/ui/task/${this.configuration.encodeParam({name: "taskId", value: taskId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/complete`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseTaskDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: completeTaskRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param xApiRequestId 
     * @param xApiCanal 
     * @param taskId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getComments(xApiRequestId: string, xApiCanal: string, taskId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseListCommentDto>;
    public getComments(xApiRequestId: string, xApiCanal: string, taskId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseListCommentDto>>;
    public getComments(xApiRequestId: string, xApiCanal: string, taskId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseListCommentDto>>;
    public getComments(xApiRequestId: string, xApiCanal: string, taskId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (xApiRequestId === null || xApiRequestId === undefined) {
            throw new Error('Required parameter xApiRequestId was null or undefined when calling getComments.');
        }
        if (xApiCanal === null || xApiCanal === undefined) {
            throw new Error('Required parameter xApiCanal was null or undefined when calling getComments.');
        }
        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling getComments.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xApiRequestId !== undefined && xApiRequestId !== null) {
            localVarHeaders = localVarHeaders.set('x-api-requestId', String(xApiRequestId));
        }
        if (xApiCanal !== undefined && xApiCanal !== null) {
            localVarHeaders = localVarHeaders.set('x-api-canal', String(xApiCanal));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/api/ui/task/${this.configuration.encodeParam({name: "taskId", value: taskId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/comments`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseListCommentDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param xApiRequestId 
     * @param xApiCanal 
     * @param taskId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTaskById(xApiRequestId: string, xApiCanal: string, taskId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseTaskDto>;
    public getTaskById(xApiRequestId: string, xApiCanal: string, taskId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseTaskDto>>;
    public getTaskById(xApiRequestId: string, xApiCanal: string, taskId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseTaskDto>>;
    public getTaskById(xApiRequestId: string, xApiCanal: string, taskId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (xApiRequestId === null || xApiRequestId === undefined) {
            throw new Error('Required parameter xApiRequestId was null or undefined when calling getTaskById.');
        }
        if (xApiCanal === null || xApiCanal === undefined) {
            throw new Error('Required parameter xApiCanal was null or undefined when calling getTaskById.');
        }
        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling getTaskById.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xApiRequestId !== undefined && xApiRequestId !== null) {
            localVarHeaders = localVarHeaders.set('x-api-requestId', String(xApiRequestId));
        }
        if (xApiCanal !== undefined && xApiCanal !== null) {
            localVarHeaders = localVarHeaders.set('x-api-canal', String(xApiCanal));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/api/ui/task/${this.configuration.encodeParam({name: "taskId", value: taskId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseTaskDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param xApiRequestId 
     * @param xApiCanal 
     * @param pagedRequestTaskFilterDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public searchTasks(xApiRequestId: string, xApiCanal: string, pagedRequestTaskFilterDto: PagedRequestTaskFilterDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponsePagedResultTaskDto>;
    public searchTasks(xApiRequestId: string, xApiCanal: string, pagedRequestTaskFilterDto: PagedRequestTaskFilterDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponsePagedResultTaskDto>>;
    public searchTasks(xApiRequestId: string, xApiCanal: string, pagedRequestTaskFilterDto: PagedRequestTaskFilterDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponsePagedResultTaskDto>>;
    public searchTasks(xApiRequestId: string, xApiCanal: string, pagedRequestTaskFilterDto: PagedRequestTaskFilterDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (xApiRequestId === null || xApiRequestId === undefined) {
            throw new Error('Required parameter xApiRequestId was null or undefined when calling searchTasks.');
        }
        if (xApiCanal === null || xApiCanal === undefined) {
            throw new Error('Required parameter xApiCanal was null or undefined when calling searchTasks.');
        }
        if (pagedRequestTaskFilterDto === null || pagedRequestTaskFilterDto === undefined) {
            throw new Error('Required parameter pagedRequestTaskFilterDto was null or undefined when calling searchTasks.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xApiRequestId !== undefined && xApiRequestId !== null) {
            localVarHeaders = localVarHeaders.set('x-api-request-id', String(xApiRequestId));
        }
        if (xApiCanal !== undefined && xApiCanal !== null) {
            localVarHeaders = localVarHeaders.set('x-api-canal', String(xApiCanal));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/api/ui/task/search`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponsePagedResultTaskDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: pagedRequestTaskFilterDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param xApiRequestId 
     * @param xApiCanal 
     * @param unassignTaskRequestDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public unassignTasks(xApiRequestId: string, xApiCanal: string, unassignTaskRequestDto: UnassignTaskRequestDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseListTaskDto>;
    public unassignTasks(xApiRequestId: string, xApiCanal: string, unassignTaskRequestDto: UnassignTaskRequestDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseListTaskDto>>;
    public unassignTasks(xApiRequestId: string, xApiCanal: string, unassignTaskRequestDto: UnassignTaskRequestDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseListTaskDto>>;
    public unassignTasks(xApiRequestId: string, xApiCanal: string, unassignTaskRequestDto: UnassignTaskRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (xApiRequestId === null || xApiRequestId === undefined) {
            throw new Error('Required parameter xApiRequestId was null or undefined when calling unassignTasks.');
        }
        if (xApiCanal === null || xApiCanal === undefined) {
            throw new Error('Required parameter xApiCanal was null or undefined when calling unassignTasks.');
        }
        if (unassignTaskRequestDto === null || unassignTaskRequestDto === undefined) {
            throw new Error('Required parameter unassignTaskRequestDto was null or undefined when calling unassignTasks.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xApiRequestId !== undefined && xApiRequestId !== null) {
            localVarHeaders = localVarHeaders.set('x-api-request-id', String(xApiRequestId));
        }
        if (xApiCanal !== undefined && xApiCanal !== null) {
            localVarHeaders = localVarHeaders.set('x-api-canal', String(xApiCanal));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/api/ui/task/unassign`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseListTaskDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: unassignTaskRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param xApiRequestId 
     * @param xApiCanal 
     * @param taskId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public unclaimTask(xApiRequestId: string, xApiCanal: string, taskId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseTaskDto>;
    public unclaimTask(xApiRequestId: string, xApiCanal: string, taskId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseTaskDto>>;
    public unclaimTask(xApiRequestId: string, xApiCanal: string, taskId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseTaskDto>>;
    public unclaimTask(xApiRequestId: string, xApiCanal: string, taskId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (xApiRequestId === null || xApiRequestId === undefined) {
            throw new Error('Required parameter xApiRequestId was null or undefined when calling unclaimTask.');
        }
        if (xApiCanal === null || xApiCanal === undefined) {
            throw new Error('Required parameter xApiCanal was null or undefined when calling unclaimTask.');
        }
        if (taskId === null || taskId === undefined) {
            throw new Error('Required parameter taskId was null or undefined when calling unclaimTask.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xApiRequestId !== undefined && xApiRequestId !== null) {
            localVarHeaders = localVarHeaders.set('x-api-requestId', String(xApiRequestId));
        }
        if (xApiCanal !== undefined && xApiCanal !== null) {
            localVarHeaders = localVarHeaders.set('x-api-canal', String(xApiCanal));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/v1/api/ui/task/${this.configuration.encodeParam({name: "taskId", value: taskId, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/unclaim`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseTaskDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
