/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProcessDto } from './processDto';


export interface ApiResponseProcessDto { 
    body?: ProcessDto;
    requestID?: string;
    timeStamp?: string;
    status?: string;
    message?: string;
    i18nErrorCode?: string;
}

