/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentDto } from './commentDto';


export interface ApiResponseCommentDto { 
    body?: CommentDto;
    requestID?: string;
    timeStamp?: string;
    status?: string;
    message?: string;
    i18nErrorCode?: string;
}

