/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiResponseMapStringObject { 
    body?: { [key: string]: object; };
    requestID?: string;
    timeStamp?: string;
    status?: string;
    message?: string;
    i18nErrorCode?: string;
}

