/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProcessHistoryDto } from './processHistoryDto';


export interface PagedResultProcessHistoryDto { 
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
    last?: boolean;
    entities?: Array<ProcessHistoryDto>;
}

