/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProcessDto } from './processDto';


export interface PagedResultProcessDto { 
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
    last?: boolean;
    entities?: Array<ProcessDto>;
}

