/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProcessInfo { 
    processDefinitionKey?: string;
    processDefinitionName?: string;
    processDefinitionId?: string;
    businessKey?: string;
    status?: string;
    startTime?: string;
    endTime?: string;
    variables?: { [key: string]: object; };
}

