/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProcessInfo } from './processInfo';


export interface ProcessDto { 
    ProcessID?: string;
    ProcessInfo?: ProcessInfo;
}

