/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProcessFilterDto { 
    processDefinitionKey?: string;
    active?: boolean;
    businessKey?: string;
    startedBefore?: string;
    startedAfter?: string;
    processDefinitionName?: string;
    processInstanceIds?: Array<string>;
    suspended?: boolean;
    tenantId?: string;
}

