/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserInfo { 
    firstName: string;
    lastName: string;
    email?: string;
    password?: string;
    groups?: Array<string>;
    tenantId?: string;
    active?: boolean;
}

